### ISSUE TITLE
How to use multiple "player_hit..." sound effects

### ISSUE THREAD

**Issue by hgrieder** [cornerstonecollege/beezy-bee#10]
Good morning - 

I wanted to use a sound effect for each different monster and I can not figure out how to rewrite the below code to incorporate more than one sound effect. Thank you!

`- (void) dieWithMonster:(BOOL)withMonster
{
    if (withMonster && [[BEESharedPreferencesHelper sharedInstance] getIsAudioEnabled])
    {
        SKAction *sound = [SKAction playSoundFileNamed:@"player_hit_monster.mp3" waitForCompletion:NO];
        __weak BEEPlayer *weakSelf = self;
        [self runAction:sound completion:^{
            [weakSelf die];
        }];
    }
    else
    {
        [self die];
    }
}
`

**Comment by luizperes** [comment]
Hi @hgrieder,

**Obs.: please update your Beezy Bee copy to the last update, as  I have just updated the code with this last commit:  https://github.com/cornerstonecollege/beezy-bee/commit/87d69f4c3baf095efd0a7e0e10fa3542c2d4274e**

First, you will need to add your own file references to the `Group` **Audio** inside the Xcode, as it is shown below:

![screen shot 2016-04-26 at 3 46 36 pm](https://cloud.githubusercontent.com/assets/6173065/14836627/5d1447a6-0bc6-11e6-9875-a54447c34313.png)

So now, for you case, you would need to change the architecture a bit... I mean, some **function parameters and values**. On your `BEEPlayer.m` file line 98, please update the method `didUpdateParentScene` to:

```
- (void)didUpdateParentScene:(SKScene *)gameScene
{
    self.zRotation = [self clamp:self.physicsBody.velocity.dy * (self.physicsBody.velocity.dy < 0 ? 0.003 : 0.001)];

    if (self.position.y < 0)
        [self die]; // We are changing this line because there was no need to call dieWithMonster:NO here
}
```

Now, we will need to change the method `dieWithMonster` on the `BEEPlayer.h`, line 24 to:

```
- (void) dieWithMonster:(BEE_MONSTER_TYPE)monsterType;
```

**Remind yourself to include the file BEEMonster.h inside the BEEPlayer.h**

Then, now everything is easier for you to incorporate more than one sound effect... in that case, the function `dieWithMonster:` would become something like that on your `BEEPlayer` file:

```
- (void) dieWithMonster:(BEE_MONSTER_TYPE)monsterType
{
    if ([[BEESharedPreferencesHelper sharedInstance] getIsAudioEnabled])
    {
        NSString *soundName = [self getSoundNameWithMonsterType:monsterType];
        SKAction *sound = [SKAction playSoundFileNamed:soundName waitForCompletion:NO];
        __weak BEEPlayer *weakSelf = self;
        [self runAction:sound completion:^{
            [weakSelf die];
        }];
    }
    else
    {
        [self die];
    }
}
```

Lastly, you would create a method call `getSoundNameWithMonsterType:` inside your `BEEPlayer.m` file, in this way:

```
- (NSString *) getSoundNameWithMonsterType:(BEE_MONSTER_TYPE)monsterType
{
  switch(monsterType)
  {
    case BMT_MONSTER1: @"name_of_your_song_one.mp3";
    case BMT_MONSTER2: @"name_of_your_song_two.mp3";
    case BMT_MONSTER3: @"name_of_your_song_three.mp3";
    case BMT_MONSTER4: @"name_of_your_song_four.mp3";
    default: return @"player_hit_monster.mp3";
  }
}
```

Well, I imagine that that would be something like that (I did not test it, but it should work). :)
I hope this helps...

thanks for the question,
Luiz.

**Comment by hgrieder** [comment]
Thank you Luiz for the detailed answer.

I made all necessary changes but ran into the below warning and the sound simply defaulted to the default line. My warning is "expression result unused."

The project builds so no errors, but the separate sounds aren't working. Code is below, thank you again!

`- (NSString *) getSoundNameWithMonsterType:(BEE_MONSTER_TYPE)monsterType
{
    switch(monsterType)
    {
        case BMT_MONSTER1: @"win.mp3";
        case BMT_MONSTER2: @"success.mp3";
        case BMT_MONSTER3: @"have_a_good_time.mp3";
        case BMT_MONSTER4: @"player_hit_monster.mp3";
        default: return @"player_hit_monster.mp3";
    }
}
- (void) dieWithMonster:(BMT_MONSTER_TYPE)monsterType
  {
  if ([[BEESharedPreferencesHelper sharedInstance] getIsAudioEnabled])
  {
      NSString *soundName = [self getSoundNameWithMonsterType:monsterType];
      SKAction *sound = [SKAction playSoundFileNamed:soundName waitForCompletion:NO];
      __weak BEEPlayer *weakSelf = self;
      [self runAction:sound completion:^{
          [weakSelf die];
      }];
  }
  else
  {
      [self die];
  }
  }
  `

**Comment by luizperes** [comment]
Hi @hgrieder,
that happens because I wrote the method `getSoundNameWithMonsterType:` wrong... the right way should be:

```
- (NSString *) getSoundNameWithMonsterType:(BEE_MONSTER_TYPE)monsterType
{
  switch(monsterType)
  {
    case BMT_MONSTER1: return @"name_of_your_song_one.mp3";
    case BMT_MONSTER2: return @"name_of_your_song_two.mp3";
    case BMT_MONSTER3: return @"name_of_your_song_three.mp3";
    case BMT_MONSTER4: return @"name_of_your_song_four.mp3";
    default: return @"player_hit_monster.mp3";
  }
}
```

I forgot to use **return** in each case.
Cheers,
Luiz

**Comment by hgrieder** [comment]
Great, thank you.

On a side note i wanted to get your opinion on something..

How would you attempt to identify the root cause of a Thread 1: Signal SIGABRT. It is happening to me in another app after the Splash screen finishes and when the first screen in the storyboard appears but i see no wrong connection anywhere.

Thanks, 

Hayden

**Comment by luizperes** [comment]
Hi @hgrieder,
I've never had this problem, although, it seems that one or more of the libraries and/or frameworks you are using are **broken**, so your program is aborting because of that..
Check it [here](http://stackoverflow.com/questions/8072135/how-to-track-down-cause-of-sigabrt)

```
SIGABRT rises when an object receives unimplemented message. How many warnings does your app have? Try surfing through them and find the ones that warn you "some object may not respond to some selector", if you clean your app from all of these, you'll most probably get it working correctly.
```
