### ISSUE TITLE
Countdown after "New Game" is tapped

### ISSUE THREAD

**Issue by damathews** [cornerstonecollege/beezy-bee#11]
This isn't really an issue but a request. I attempted to add this in to the game but was not able to go down the right path. Since you are more familiar with the project/code files, could you assist in adding a 3, 2, 1, Go! after a user taps the New Game on the main menu. I think the restart icon within the game is fine, but I think it would be nice to give a heads up when the game is initially about to start.

As always, thank you very much!!

**Comment by luizperes** [comment]
Hi @damathews,
I think that the easiest way to that would be creating a [NSTimer](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSTimer_Class/) for that...

So, inside your  `BEENewGameView.m` file line 64 you can rename the function `createNewGameWithParentScene:` to `startNewGameWithParentScene:` in this way:

```
- (void) startNewGameWithParentScene:(SKScene *)parent
{
    [BEESessionHelper sharedInstance].currentScreen = BST_GAME;
    [BEESessionHelper sharedInstance].userScore = 0;
    [BEESessionHelper sharedInstance].isGameOver = NO;

    SKLabelNode *backLabel = [self createLabelWithParentScene:parent keyForName:@"back"];
    [self setLabelNode:backLabel position:CGPointMake(backLabel.frame.size.width / 2 + 10, parent.size.height - backLabel.frame.size.height - 10)];

    pointLabel = [SKLabelNode labelNodeWithFontNamed:[[BEESessionHelper sharedInstance] getLocalizedStringForName:@"font_style"]];
    pointLabel.fontColor = [SKColor blackColor];
    [parent addChild:pointLabel];
    [self setLabelNode:pointLabel position:CGPointMake(CGRectGetMidX(parent.frame), parent.size.height - backLabel.frame.size.height - 50)];
    pointLabel.fontSize = 80;

    __weak BEEPlayer *player = [BEEPlayer playerWithParent:parent];
    if (parent.size.height < 500)
    {
        player.yScale = 0.25;
        player.xScale = 0.25;
    }
    else
    {
        player.yScale = 0.35;
        player.xScale = 0.35;
    }

    [self.objArray addObject:player];

    __weak SKLabelNode *weakScoreLabel = pointLabel;
    [self.objArray addObject:weakScoreLabel];
}
```

Above that new function (as you still need to implement the function `createNewGameWithParentScene:`) you would redeclare the `createNewGameWithParentScene:` as following:

```
- (void) createNewGameWithParentScene:(SKScene *)parent
{
  if ([parent isKindOfClass:[GameScene class]])
  {
      self.parent = (GameScene *)parent;
       __weak BEENewGameView *weakSelf = self;
      [self.parent resetTimerDelegate];
      [self.parent.timerDelegateArr addObject:weakSelf];
  } 

  // here it will fire from 1 to 1 second.
  NSTimer *myTimer = [NSTimer scheduledTimerWithTimeInterval:1.0 target:self selector:@selector(timerDidFire:) userInfo:nil repeats:YES]; 
}

- (void) timerDidFire:(NSTimer *)timer 
{
    self.counter -= 1; // self.counter is a global variable that starts with 3 (seconds), for example...

   // here you can show 3...2...1...go, depending on the self.counter var...

  if (self.counter == 0)
  {
     // reinitialize the self.counter var (in case that the user dies)
     self.counter = 3;
     [timer invalidate];

     // here you would call the function startNewGameWithParentScene:
     [self startNewGameWithParentScene:self.parent];
  }
}

```

I think that this should help.. if not, reach out to me again.
Thanks,
Luiz.

**Comment by damathews** [comment]
The last part received errors. Do I need to add an implementation or a Property?
![screen shot 2016-04-27 at 8 42 59 pm](https://cloud.githubusercontent.com/assets/17294944/14872567/92723a2a-0cbb-11e6-8125-5db70c1263a8.png)

**Comment by damathews** [comment]
Sorry, I thought the errors would have shown up in the screenshots.

Warning appeared under "// here it will fire from 1 to 1 second."

Errors appeared on "self.counter -= 1", " if (self.counter == 0)", and "self.counter = 3;"

**Comment by luizperes** [comment]
Hi @damathews,
yeah.. you will need to implement a property called `counter`. Inside the same file, add it on line 24, as following:

```
@interface BEENewGameView ()

@property (nonatomic) NSMutableArray *objArray;
@property (nonatomic) NSArray *playerArray;
@property (nonatomic, weak) GameScene *parent;
@property (nonatomic) NSMutableArray *monsterArray;
@property (nonatomic) NSInteger count; 

@end
```

Then, you will need to initialize it... so, inside the function `createNewGameWithParentScene:`, please add an initialization for it as:

```
- (void) createNewGameWithParentScene:(SKScene *)parent
{
  if ([parent isKindOfClass:[GameScene class]])
  {
      self.parent = (GameScene *)parent;
       __weak BEENewGameView *weakSelf = self;
      [self.parent resetTimerDelegate];
      [self.parent.timerDelegateArr addObject:weakSelf];
  } 

  self.counter = 3;

  // here it will fire from 1 to 1 second.
  NSTimer *myTimer = [NSTimer scheduledTimerWithTimeInterval:1.0 target:self selector:@selector(timerDidFire:) userInfo:nil repeats:YES]; 
}
```

It should work now... :)
Luiz.

**Comment by luizperes** [comment]
One more thing is... you can even take the initialization of the property `self.counter` off (we can do it because now we are reinitializing inside the method `createNewGameWithParentScene:`) the method `timerDidFire` as below:

```
- (void) timerDidFire:(NSTimer *)timer 
{
    self.counter -= 1; // self.counter is a global variable that starts with 3 (seconds), for example...

   // here you can show 3...2...1...go, depending on the self.counter var...

  if (self.counter == 0)
  {
     [timer invalidate];

     // here you would call the function startNewGameWithParentScene:
     [self startNewGameWithParentScene:self.parent];
  }
}
```

**Comment by damathews** [comment]
I will have to work with it more this weekend. The Timer is not being recognized so it does not show up at the start of the game, but it does delay 3 seconds. The error is at NSTimer *myTimer

**Comment by luizperes** [comment]
Hi @damathews,
in fact there were some small problems... that happened because I only wrote the code in "my mind"... Now I tested on my Xcode, and so I generated a **Gist** for you.

Please see the code [here](https://gist.github.com/luizperes/7c4c34c0198e4949cb5d62f1b3e14fef)

**Comment by damathews** [comment]
That's awesome. Thank you for your help. The timer works but it is not
being displayed. It's not really a big deal, but is this due to the
__Unused variable of
__unused NSTimer *myTimer = [NSTimer scheduledTimerWithTimeInterval:1.0
target:self selector:@selector(timerDidFire:) userInfo:nil repeats:YES];

**Comment by luizperes** [comment]
Hi @damathews,
for that, you will need to have the countdown images (or make it using SKLabel)... I did not implement it because we do not have them in our project...

I think that you would show the new node inside the `timerDidFire:`...

try to find the line that has the comment: `// here you can show 3...2...1...go, depending on the self.counter var...`

There is a tutorial [here](https://makeapppie.com/2014/04/10/slippyflippy-1-1-how-to-make-a-countdown-timer-in-sprite-kit/) for that... (I did not test it)

Thanks,
Luiz.

**Comment by damathews** [comment]
That's fine. I will work on it. Thank you so much for your help adding in
the code. That was really awesome!
