### ISSUE TITLE
Adding Additional Features

### ISSUE THREAD

**Issue by hgrieder** [cornerstonecollege/beezy-bee#12]
Good Afternoon -

Have you thought of, or tried to add additional characters and perhaps make them in-app purchases?

Thanks, 

Hayden

**Comment by luizperes** [comment]
Hi @hgrieder,
we did not consider in-app purchases as the app was developed with the aiming of learning how to make small games on SpriteKit.. (I was teaching my students some basic concepts of game development and Objective-C). Although, it is easy to add extra characters (not only that, but take a look to `BEEPlayer`, `BEEMonster` and perhaps `BEEItem`).

Thanks,
Luiz
