### ISSUE TITLE
Different scoring metrics

### ISSUE THREAD

**Issue by damathews** [cornerstonecollege/beezy-bee#13]
Hey Luiz,

How difficult would it be to change the format of the scoring function? I would like to test a time interval and perhaps each flower and honeycomb multiplies the clock time. That way if you were to go for a long time but are missing flowers, you are still gathering points.

Thank you!

**Comment by luizperes** [comment]
You can do that by including the `[BEESessionHelper sharedInstance].userScore += 1;` inside the method `didUpdateTimerWithParentScene:` on the `BEENewGameView.m` line 160 or you can work with the method `scoreIsSpecial:` inside the `BEEPlayer.m` file.

**Comment by damathews** [comment]
Perfect. That is exactly what I was going for!
