### ISSUE TITLE
Multiple Sound Effects Issue

### ISSUE THREAD

**Issue by hgrieder** [cornerstonecollege/beezy-bee#14]
Good afternoon - 

I am having a issue with preloading sound effects.. I am trying to preload all of the sound effects because it seems that the initial playerhitmonster sound effect makes the game lag. So is there any way to load them when the app starts?

Thanks,

Hayden

**Comment by luizperes** [comment]
Hi Hayden, I don't know if there is one, but I don't think that the game lag is due to the audio, once `SKAction`s run on the background...

Luiz.
