### ISSUE TITLE
Show only Top 3 scores after

### ISSUE THREAD

**Issue by damathews** [cornerstonecollege/beezy-bee#15]
Hi,

I added an additional character so I could test out various physicsworld gravity settings, so now I have 4 total characters. When I go to the Scores screen it shows all 4 but I only want to show the top 3.

The code looks to pull scores on the BEEScoreView.m file with:

```
NSDictionary *scores = [[BEESharedPreferencesHelper sharedInstance] getScores];
    NSArray *keysOrdered = [scores keysSortedByValueUsingComparator:^NSComparisonResult(id  _Nonnull obj1, id  _Nonnull obj2) {
        return [obj2 compare:obj1];
```

Is there an easy way to limit the results to just the top 3?

Thank you!

**Comment by luizperes** [comment]
Hi,
the problem is actually at the `line 80` on the `BEEScoreView.m`:

```
float dec = 0;
for (NSNumber *type in keysOrdered)
{
...
```

The `foreach` above will go through all your characters, so you should use a `for` instead. :)

```
for (int i = 0; i < [keysOrdered count] - 1; i++) // -1 excludes the last one
{
   NSNumber *type = keysOrdered[i];
...
```

Sorry for delaying your answer,
Luiz
